name: production
on:
  branch:
    - main
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - main

protection_rules:
  required_reviewers:
    - joelschrock
  wait_timer: 5
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false
