name: 🚀 Deploy Container to Heroku

on:
  workflow_run:
    workflows: ["🔄 CI/CD Pipeline - Test & Build"]
    types: [completed]
    branches: [ main ]
  workflow_dispatch:

env:
  HEROKU_APP_NAME: ai-acquisition-agent

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔐 Setup Heroku CLI
      run: |
        # Check if required secrets are available
        if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
          echo "❌ HEROKU_API_KEY secret is missing!"
          echo "Please add HEROKU_API_KEY to your GitHub repository secrets"
          exit 1
        fi
        
        if [ -z "${{ secrets.HEROKU_EMAIL }}" ]; then
          echo "❌ HEROKU_EMAIL secret is missing!"
          echo "Please add HEROKU_EMAIL to your GitHub repository secrets"
          exit 1
        fi
        
        echo "✅ Required secrets found"
        
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
        
        # Add Heroku to PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Set Heroku API key as environment variable
        export HEROKU_API_KEY="${{ secrets.HEROKU_API_KEY }}"
        export HEROKU_EMAIL="${{ secrets.HEROKU_EMAIL }}"
        
        # Create .netrc file for non-interactive authentication
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        echo "machine git.heroku.com" >> ~/.netrc
        echo "  login ${{ secrets.HEROKU_EMAIL }}" >> ~/.netrc
        echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
        chmod 600 ~/.netrc
        
        # Set HEROKU_API_KEY environment variable for CLI
        echo "export HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> ~/.bashrc
        source ~/.bashrc
        
        # Verify authentication
        echo "🔐 Testing Heroku authentication..."
        HEROKU_API_KEY="${{ secrets.HEROKU_API_KEY }}" heroku auth:whoami || {
          echo "❌ Direct authentication failed, trying with .netrc..."
          # Test if .netrc authentication works
          curl -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
               -H "Accept: application/vnd.heroku+json; version=3" \
               https://api.heroku.com/account
        }
        
        # Ensure app is configured for Docker deployment
        heroku stack:set container --app ${{ env.HEROKU_APP_NAME }} || echo "App already set to container stack"
        
        # Remove any existing buildpacks to force Docker-only deployment
        heroku buildpacks:clear --app ${{ env.HEROKU_APP_NAME }} || echo "No buildpacks to clear"
        
        # Explicitly set no buildpacks
        heroku buildpacks:set --index 1 --app ${{ env.HEROKU_APP_NAME }} || echo "No buildpacks to set"
        
        # Verify we're using container stack
        echo "🔍 Current Heroku stack:"
        heroku stack --app ${{ env.HEROKU_APP_NAME }}
        
        # Ensure no buildpacks are configured
        echo "🔍 Current buildpacks:"
        heroku buildpacks --app ${{ env.HEROKU_APP_NAME }} || echo "No buildpacks configured"
        
        # Check if app exists and create it if needed
        echo "🔧 Checking if app exists..."
        if ! heroku apps:info --app ${{ env.HEROKU_APP_NAME }} >/dev/null 2>&1; then
          echo "📱 Creating new Heroku app with container stack..."
          heroku create ${{ env.HEROKU_APP_NAME }} --stack container
        else
          echo "✅ App already exists"
          # Ensure existing app is on container stack
          echo "🔧 Setting app to container stack..."
          heroku stack:set container --app ${{ env.HEROKU_APP_NAME }}
        fi
        
        # Verify app.json configuration
        echo "🔧 Verifying container deployment configuration..."
        cat app.json
        
        # Final authentication verification
        echo "🔐 Verifying Heroku authentication..."
        if heroku auth:whoami; then
          echo "✅ Heroku authentication successful"
        else
          echo "❌ Heroku authentication failed - cannot proceed"
          exit 1
        fi
        
    - name: 🐳 Build and Push Docker Container
      run: |
        # Verify we have the necessary files
        echo "🔍 Checking for required files..."
        ls -la
        echo "📦 Package files:"
        ls -la package*
        
        # Try heroku container:push first, fallback to manual Docker if needed
        echo "🚀 Attempting heroku container:push..."
        if heroku container:push web --force --app ${{ env.HEROKU_APP_NAME }}; then
          echo "✅ heroku container:push succeeded"
        else
          echo "⚠️ heroku container:push failed, trying manual Docker deployment..."
          
          # Login to Heroku Container Registry
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=${{ secrets.HEROKU_EMAIL }} --password-stdin registry.heroku.com
          
          # Build Docker image
          echo "🏗️ Building Docker image..."
          docker build -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web .
          
          # Push to Heroku Container Registry
          echo "📤 Pushing to Heroku Container Registry..."
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          
          # Release the container
          echo "🚀 Releasing container..."
          heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
        fi
        
        # Verify container is running
        echo "🔍 Verifying container deployment..."
        heroku ps --app ${{ env.HEROKU_APP_NAME }}
        
    - name: 🔧 Configure environment variables
      run: |
        heroku config:set NODE_ENV=production --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set PORT=3000 --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set TEST_MODE=false --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set SHOW_JSON_PAYLOAD=false --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set ASSIGNMENT_FEE_MIN=10000 --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set DEFAULT_DISPO_WINDOW=45 --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --app ${{ env.HEROKU_APP_NAME }}
        
        # Set additional server configuration
        heroku config:set HOST=0.0.0.0 --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set LOG_LEVEL=info --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set OPENAI_MODEL=gpt-4o-mini --app ${{ env.HEROKU_APP_NAME }}
        # Set Slack configuration with verification
        echo "🔐 Setting Slack configuration..."
        heroku config:set SLACK_BOT_TOKEN="${{ secrets.SLACK_BOT_TOKEN }}" --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set SLACK_SIGNING_SECRET="${{ secrets.SLACK_SIGNING_SECRET }}" --app ${{ env.HEROKU_APP_NAME }}
        heroku config:set SLACK_APP_TOKEN="${{ secrets.SLACK_APP_TOKEN }}" --app ${{ env.HEROKU_APP_NAME }}
        
        # Verify Slack secrets are set
        echo "🔍 Verifying Slack secrets..."
        SLACK_BOT_TOKEN=$(heroku config:get SLACK_BOT_TOKEN --app ${{ env.HEROKU_APP_NAME }})
        SLACK_SIGNING_SECRET=$(heroku config:get SLACK_SIGNING_SECRET --app ${{ env.HEROKU_APP_NAME }})
        SLACK_APP_TOKEN=$(heroku config:get SLACK_APP_TOKEN --app ${{ env.HEROKU_APP_NAME }})
        
        if [ -n "$SLACK_BOT_TOKEN" ] && [ "$SLACK_BOT_TOKEN" != "null" ]; then
          echo "✅ SLACK_BOT_TOKEN set successfully"
        else
          echo "❌ SLACK_BOT_TOKEN not set or empty"
        fi
        
        if [ -n "$SLACK_SIGNING_SECRET" ] && [ "$SLACK_SIGNING_SECRET" != "null" ]; then
          echo "✅ SLACK_SIGNING_SECRET set successfully"
        else
          echo "❌ SLACK_SIGNING_SECRET not set or empty"
        fi
        
        if [ -n "$SLACK_APP_TOKEN" ] && [ "$SLACK_APP_TOKEN" != "null" ]; then
          echo "✅ SLACK_APP_TOKEN set successfully"
        else
          echo "❌ SLACK_APP_TOKEN not set or empty"
        fi
        
    - name: 🗄️ Setup MongoDB (Use Existing Atlas)
      run: |
        echo "🗄️ Setting up MongoDB connection to your existing Atlas cluster..."
        
        # Set MongoDB URI from your existing Atlas cluster
        if [ -n "${{ secrets.MONGODB_URI }}" ]; then
          echo "✅ Using your existing MongoDB Atlas URI"
          heroku config:set MONGODB_URI="${{ secrets.MONGODB_URI }}" --app ${{ env.HEROKU_APP_NAME }}
        else
          echo "⚠️ MONGODB_URI secret not found in GitHub"
          echo "Please add your MongoDB Atlas connection string to GitHub secrets:"
          echo "Name: MONGODB_URI"
          echo "Value: mongodb+srv://username:password@cluster.mongodb.net/database"
          exit 1
        fi
        
        # Verify MongoDB URI is set
        echo "🔍 Verifying MongoDB configuration..."
        MONGODB_URI=$(heroku config:get MONGODB_URI --app ${{ env.HEROKU_APP_NAME }})
        if [ -n "$MONGODB_URI" ] && [ "$MONGODB_URI" != "null" ]; then
          echo "✅ MongoDB URI set successfully: $MONGODB_URI"
        else
          echo "❌ MongoDB URI not set properly"
          exit 1
        fi
        
        # Verify all environment variables are set
        echo "🔍 Verifying all environment variables..."
        heroku config --app ${{ env.HEROKU_APP_NAME }}
        
        # Restart the container to pick up new environment variables
        echo "🔄 Restarting container to apply new environment variables..."
        heroku restart --app ${{ env.HEROKU_APP_NAME }}
        
        # Wait for restart
        echo "⏳ Waiting for container restart..."
        sleep 30
        
    - name: ✅ Health check
      run: |
        # Wait for deployment and check app status
        echo "⏳ Waiting for app to start..."
        sleep 60
        
        # Check app status first
        echo "🔍 Checking app status..."
        heroku ps --app ${{ env.HEROKU_APP_NAME }}
        
        # Check app logs for any errors
        echo "📋 Checking recent app logs..."
        heroku logs --tail --app ${{ env.HEROKU_APP_NAME }} | head -20
        
        # Test application health with better error handling
        echo "🏥 Testing health endpoint..."
        echo "🔗 Health URL: https://${{ env.HEROKU_APP_NAME }}.herokuapp.com/health"
        
        # Try multiple times with increasing delays
        for i in {1..3}; do
          echo "🔄 Health check attempt $i..."
          if curl -f -v https://${{ env.HEROKU_APP_NAME }}.herokuapp.com/health; then
            echo "✅ Health check passed on attempt $i"
            break
          else
            echo "⚠️ Health check attempt $i failed"
            if [ $i -lt 3 ]; then
              echo "⏳ Waiting 30 seconds before retry..."
              sleep 30
            else
              echo "❌ All health check attempts failed"
              echo "🔍 Final app status:"
              heroku ps --app ${{ env.HEROKU_APP_NAME }}
              echo "📋 Final app logs:"
              heroku logs --tail --app ${{ env.HEROKU_APP_NAME }} | head -30
              exit 1
            fi
          fi
        done
        
        echo "✅ Health check completed successfully"
        
    - name: 📊 Deployment summary
      run: |
        echo "🎉 Heroku container deployment completed successfully!"
        echo "🌐 Your AI Agent is now live at: https://${{ env.HEROKU_APP_NAME }}.herokuapp.com"
        echo "📱 Update your Slack app URL to: https://${{ env.HEROKU_APP_NAME }}.herokuapp.com/slack/events"
        echo "🐳 Deployed using Docker containers for better reliability and consistency"
